# Generated by Django 4.1.2 on 2022-10-30 03:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=256)),
                ('restaurant_owner_name', models.CharField(max_length=100)),
                ('restaurant_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Must add 880', regex='^\\+?(88)01[3-9][0-9]{8}$')])),
                ('restaurant_address', models.CharField(max_length=100)),
                ('restaurant_area', models.CharField(max_length=100)),
                ('restaurant_city', models.CharField(max_length=100)),
                ('restaurant_country', models.CharField(max_length=100)),
                ('restaurant_open_time', models.TimeField()),
                ('restaurant_closing_time', models.TimeField()),
                ('restaurant_type', models.CharField(max_length=100)),
                ('restaurant_registration_date', models.DateTimeField()),
                ('root_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.CharField(choices=[('-1', 'Negative'), ('0', 'No review'), ('1', 'Positive')], max_length=20)),
                ('total_ordered', models.PositiveIntegerField(default=0)),
                ('restaurant_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_main.restaurantmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_offer', models.ImageField(upload_to='restaurant_offer_menu/')),
                ('days', models.CharField(blank=True, max_length=20, null=True)),
                ('validate_until', models.DateField(blank=True, null=True)),
                ('restaurant_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_main.restaurantmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='restaurant_image/')),
                ('image_2', models.ImageField(blank=True, upload_to='restaurant_image/')),
                ('image_3', models.ImageField(blank=True, upload_to='restaurant_image/')),
                ('image_4', models.ImageField(blank=True, upload_to='restaurant_image/')),
                ('restaurant_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_main.restaurantmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_image')),
                ('food_description', models.TextField(blank=True, null=True)),
                ('food_price', models.PositiveIntegerField()),
                ('veg', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_main.restaurantmodel')),
            ],
        ),
    ]
