# Generated by Django 4.1.2 on 2022-10-30 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_menu', to='App_main.restaurantmodel'),
        ),
        migrations.AlterField(
            model_name='restaurantimagesmodel',
            name='restaurant_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_images', to='App_main.restaurantmodel'),
        ),
        migrations.AlterField(
            model_name='restaurantmenumodel',
            name='restaurant_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_special_menu', to='App_main.restaurantmodel'),
        ),
        migrations.AlterField(
            model_name='restaurantmodel',
            name='restaurant_city',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Rajshahi', 'Rajshahi'), ('Rongpur', 'Rongpur'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantratingmodel',
            name='restaurant_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_rating', to='App_main.restaurantmodel'),
        ),
    ]
