# Generated by Django 4.1.2 on 2022-10-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0002_alter_menuitems_restaurant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItemsModel',
        ),
    ]
