# Generated by Django 4.1.2 on 2022-10-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0004_cartmodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='restaurant_main_image'),
        ),
    ]
