# Generated by Django 4.1.2 on 2022-10-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0005_restaurantmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='restuarant_service_type',
            field=models.CharField(default='Order Online', max_length=100),
        ),
    ]
