# Generated by Django 4.1.2 on 2022-11-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0008_rename_order_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Processing', 'Processing'), ('Rejected', 'Rejected'), ('Collected', 'Collected'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='Requested', max_length=20),
        ),
    ]
