# Generated by Django 4.1.2 on 2022-11-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0009_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('In_cart', 'In_cart'), ('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Processing', 'Processing'), ('Rejected', 'Rejected'), ('Collected', 'Collected'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='In_cart', max_length=20),
        ),
    ]
