# Generated by Django 4.1.2 on 2022-11-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0010_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
