# Generated by Django 4.1.2 on 2022-11-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0011_restaurantmodel_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_restaurant', to='App_main.restaurantmodel'),
            preserve_default=False,
        ),
    ]
