# Generated by Django 4.1.2 on 2022-11-13 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_main', '0012_ordermodel_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_man_of_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
