# Generated by Django 4.1.2 on 2022-11-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0013_ordermodel_delivery_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='restaurant_zone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('In_cart', 'In_cart'), ('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Processing', 'Processing'), ('Rejected', 'Rejected'), ('Collected', 'Collected'), ('Find_Heros', 'Find_Heros'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='In_cart', max_length=20),
        ),
    ]
