# Generated by Django 4.1.2 on 2022-11-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0014_restaurantmodel_restaurant_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('In_cart', 'In_cart'), ('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Processing', 'Processing'), ('Rejected', 'Rejected'), ('Collected', 'Collected'), ('Found_Heros', 'Found_Heros'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='In_cart', max_length=20),
        ),
    ]
