# Generated by Django 4.1.2 on 2022-12-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0015_ordermodel_billing_address_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmodel',
            name='restaurant_registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
