# Generated by Django 4.1.2 on 2022-11-13 13:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryManProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nid', models.CharField(max_length=17)),
                ('primary_phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Must add 880', regex='^\\+?(88)01[3-9][0-9]{8}$')], verbose_name='Mobile phone')),
                ('secondary_phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Must add 880', regex='^\\+?(88)01[3-9][0-9]{8}$')], verbose_name='Mobile phone')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='delivery_man_profile_pic/')),
                ('full_home_address', models.CharField(blank=True, max_length=100)),
                ('full_present_address', models.CharField(blank=True, max_length=100)),
                ('area_coverage', models.TextField()),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_man_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
