# Generated by Django 4.1.2 on 2022-11-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_delivery_man', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymanprofilemodel',
            name='employee_id',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
