# Generated by Django 4.1.2 on 2022-11-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_delivery_man', '0002_deliverymanprofilemodel_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymanprofilemodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
