# Generated by Django 4.1.2 on 2022-11-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_delivery_man', '0003_deliverymanprofilemodel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymanprofilemodel',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
