# Generated by Django 4.1.2 on 2022-10-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0002_rename_profile_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Rajshahi', 'Rajshahi'), ('Rongpur', 'Rongpur'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='house',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
