# Generated by Django 4.1.2 on 2022-12-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0003_alter_profilemodel_area_alter_profilemodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
