# Generated by Django 4.1.2 on 2022-12-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0004_profilemodel_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
